"""empty message

Revision ID: 1f30ab20bc2b
Revises: 1571356bdb69
Create Date: 2021-07-12 19:05:07.444045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f30ab20bc2b'
down_revision = '1571356bdb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labs', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_like')
    # ### end Alembic commands ###
