"""empty message

Revision ID: 546de115325a
Revises: 6fb1d8137403
Create Date: 2021-07-13 19:52:24.171890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546de115325a'
down_revision = '6fb1d8137403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('labs', sa.Text(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
