"""empty message

Revision ID: 6fb1d8137403
Revises: 1f30ab20bc2b
Create Date: 2021-07-13 15:14:36.040203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb1d8137403'
down_revision = '1f30ab20bc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('labcode', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'labcode')
    # ### end Alembic commands ###
